[package]
name = "bfrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive", "string"] }
parking_lot = "0.12.1"
x86asm = "0.1.0"
